name: Issue Manager

on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 1-5" # run at 5:17 on Monday to Friday
  # We only use the issue manager for auto-closing, so we only need the cron trigger.
  # issue_comment:
  #   types:
  #     - created
  #     - edited
  # issues:
  #   types:
  #     - labeled

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "$schema": "https://raw.githubusercontent.com/tiangolo/issue-manager/master/schema.json",
                "waiting for input": {
                    "delay": "P30DT0H0M0S",
                    "message": "Auto-closing this issue after waiting for input for a month. If anyone finds the time to provide the requested information, please re-open the issue and we will continue handling it.",
                    "remove_label_on_comment": true,
                    "remove_label_on_close": false
                },
                "waiting for fix confirmation": {
                    "delay": "P30DT0H0M0S",
                    "message": "Auto-closing this issue after waiting for a fix confirmation for a month. If anyone still experiences this issue, please re-open the issue with updated information so we can continue working on a fix.",
                    "remove_label_on_comment": true,
                    "remove_label_on_close": false
                },
                "waiting for release": {
                    "delay": "P3650DT0H0M0S",
                    "message": "That was 10 years ago, I think we can close this now.",
                    "remove_label_on_comment": true,
                    "remove_label_on_close": false
                },
                "waiting for resources": {
                    "delay": "P3650DT0H0M0S",
                    "message": "That was 10 years ago, I think we can close this now.",
                    "remove_label_on_comment": true,
                    "remove_label_on_close": false
                }
            }
